=head1 NAME

SPOPS::Manual::Error - SPOPS Error handling

=head1 DESCRIPTION

Error handling in SPOPS has changed. Please see
L<SPOPS::Manual::Exceptions|SPOPS::Manual::Exceptions>.

=head1 COPYRIGHT

Copyright (c) 2001-2004 Chris Winters. All rights reserved.

See L<SPOPS::Manual|SPOPS::Manual> for license.

=head1 AUTHORS

Chris Winters E<lt>chris@cwinters.comE<gt>
